// <auto-generated />
using System;
using GisysConsultBonusSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GisysConsultBonusSystem.Migrations
{
    [DbContext(typeof(ConsultContext))]
    [Migration("20190511152529_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GisysConsultBonusSystem.Models.Bonus", b =>
                {
                    b.Property<int>("BonusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BonusDate");

                    b.Property<decimal>("BonusPot")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("ChargedHours")
                        .HasColumnType("int");

                    b.Property<int>("ChargedHoursWithBonus")
                        .HasColumnType("int");

                    b.Property<int>("ConsultID")
                        .HasColumnType("int");

                    b.Property<int>("NetResult")
                        .HasColumnType("int");

                    b.Property<int>("PeriodOfEmployment")
                        .HasColumnType("int");

                    b.HasKey("BonusID");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("GisysConsultBonusSystem.Models.Consult", b =>
                {
                    b.Property<int>("ConsultID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EmploymentDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConsultID");

                    b.ToTable("Consults");
                });
#pragma warning restore 612, 618
        }
    }
}
